country = {
    1: "Japan",
    8: "Anguilla",
    9: "Antigua and Barbuda",
    10: "Argentina",
    11: "Aruba",
    12: "Bahamas",
    13: "Barbados",
    14: "Belize",
    15: "Bolivia",
    16: "Brazil",
    17: "British Virgin Islands",
    18: "Canada",
    19: "Cayman Islands",
    20: "Chile",
    21: "Colombia",
    22: "Costa Rica",
    23: "Dominica",
    24: "Dominican Republic",
    25: "Ecuador",
    26: "El Salvador",
    27: "French Guiana",
    28: "Grenada",
    29: "Guadeloupe",
    30: "Guatemala",
    31: "Guyana",
    32: "Haiti",
    33: "Honduras",
    34: "Jamaica",
    35: "Martinique",
    36: "Mexico",
    37: "Montserrat",
    38: "Netherlands Antilles",
    39: "Nicaragua",
    40: "Panama",
    41: "Paraguay",
    42: "Peru",
    43: "St. Kitts and Nevis",
    44: "St. Lucia",
    45: "St. Vincent and the Grenadines",
    46: "Suriname",
    47: "Trinidad and Tobago",
    48: "Turks and Caicos Islands",
    49: "United States",
    50: "Uruguay",
    51: "US Virgin Islands",
    52: "Venezuela",
    64: "Albania",
    65: "Australia",
    66: "Austria",
    67: "Belgium",
    68: "Bosnia and Herzegovina",
    69: "Botswana",
    70: "Bulgaria",
    71: "Croatia",
    72: "Cyprus",
    73: "Czech Republic",
    74: "Denmark",
    75: "Estonia",
    76: "Finland",
    77: "France",
    78: "Germany",
    79: "Greece",
    80: "Hungary",
    81: "Iceland",
    82: "Ireland",
    83: "Italy",
    84: "Latvia",
    85: "Lesotho",
    86: "Lichtenstein",
    87: "Lithuania",
    88: "Luxembourg",
    89: "F.Y.R of Macedonia",
    90: "Malta",
    91: "Montenegro",
    92: "Mozambique",
    93: "Namibia",
    94: "Netherlands",
    95: "New Zealand",
    96: "Norway",
    97: "Poland",
    98: "Portugal",
    99: "Romania",
    100: "Russia",
    101: "Serbia",
    102: "Slovakia",
    103: "Slovenia",
    104: "South Africa",
    105: "Spain",
    106: "Swaziland",
    107: "Sweden",
    108: "Switzerland",
    109: "Turkey",
    110: "United Kingdom",
    111: "Zambia",
    112: "Zimbabwe",
    113: "Azerbaijan",
    114: "Mauritania (Islamic Republic of Mauritania)",
    115: "Mali (Republic of Mali)",
    116: "Niger (Republic of Niger)",
    117: "Chad (Republic of Chad)",
    118: "Sudan (Republic of the Sudan)",
    119: "Eritrea (State of Eritrea)",
    120: "Djibouti (Republic of Djibouti)",
    121: "Somalia (Somali Republic)",
    128: "Taiwan",
    136: "South Korea",
    144: "Hong Kong",
    145: "Macao",
    152: "Indonesia",
    153: "Singapore",
    154: "Thailand",
    155: "Philippines",
    156: "Malaysia",
    160: "China",
    168: "U.A.E.",
    169: "India",
    170: "Egypt",
    171: "Oman",
    172: "Qatar",
    173: "Kuwait",
    174: "Saudi Arabia",
    175: "Syria",
    176: "Bahrain",
    177: "Jordan",
}

state = {
    'Japan': {1: 'Japan', 2: 'Tokyo', 3: 'Hokkaido', 4: 'Aomori', 5: 'Iwate', 6: 'Miyagi', 7: 'Akita', 8: 'Yamagata',
              9: 'Fukushima', 10: 'Ibaraki', 11: 'Tochigi', 12: 'Gunma', 13: 'Saitama', 14: 'Chiba', 15: 'Kanagawa',
              16: 'Toyama', 17: 'Ishikawa', 18: 'Fukui', 19: 'Yamanashi', 20: 'Nagano', 21: 'Niigata', 22: 'Gifu',
              23: 'Shizuoka', 24: 'Aichi', 25: 'Mie', 26: 'Shiga', 27: 'Kyoto', 28: 'Osaka', 29: 'Hyogo', 30: 'Nara',
              31: 'Wakayama', 32: 'Tottori', 33: 'Shimane', 34: 'Okayama', 35: 'Hiroshima', 36: 'Yamaguchi',
              37: 'Tokushima', 38: 'Kagawa', 39: 'Ehime', 40: 'Kochi', 41: 'Fukuoka', 42: 'Saga', 43: 'Nagasaki',
              44: 'Kumamoto', 45: 'Oita', 46: 'Miyazaki', 47: 'Kagoshima', 48: 'Okinawa'},
    'Anguilla': {1: 'Anguilla'},
    'Antigua and Barbuda': {1: 'Antigua and Barbuda', 2: 'Saint John', 3: 'Barbuda', 4: 'Saint George', 5: 'Saint Mary',
                            6: 'Saint Paul', 7: 'Saint Peter', 8: 'Saint Philip'},
    'Argentina': {1: 'Argentina', 2: 'Distrito Federal', 3: 'Buenos Aires', 4: 'Catamarca', 5: 'Chaco', 6: 'Chubut',
                  7: 'Córdoba', 8: 'Corrientes', 9: 'Entre Ríos', 10: 'Formosa', 11: 'Jujuy', 12: 'La Pampa',
                  13: 'La Rioja', 14: 'Mendoza', 15: 'Misiones', 16: 'Neuquén', 17: 'Río Negro', 18: 'Salta',
                  19: 'San Juan', 20: 'San Luis', 21: 'Santa Cruz', 22: 'Santa Fe', 23: 'Santiago del Estero',
                  24: 'Tierra del Fuego, Antártida e Islas del Atlántico Sur', 25: 'Tucumán'},
    'Aruba': {1: 'Aruba'},
    'Bahamas': {1: 'Bahamas'},
    'Barbados': {1: 'Barbados'},
    'Belize': {1: 'Belize', 2: 'Cayo', 3: 'Belize', 4: 'Corozal', 5: 'Orange Walk', 6: 'Stann Creek', 7: 'Toledo'},
    'Bolivia': {1: 'Bolivia', 2: 'La Paz', 3: 'Chuquisaca', 4: 'Cochabamba', 5: 'El Beni', 6: 'Oruro', 7: 'Pando',
                8: 'Potosí', 9: 'Santa Cruz', 10: 'Tarija'},
    'Brazil': {1: 'Brazil', 2: 'Distrito Federal', 3: 'Acre', 4: 'Alagoas', 5: 'Amapá', 6: 'Amazonas', 7: 'Bahia',
               8: 'Ceará', 9: 'Espírito Santo', 10: 'Mato Grosso do Sul', 11: 'Maranhão', 12: 'Mato Grosso',
               13: 'Minas Gerais', 14: 'Pará', 15: 'Paraíba', 16: 'Paraná', 17: 'Piauí', 18: 'Rio de Janeiro',
               19: 'Rio Grande do Norte', 20: 'Rio Grande do Sul', 21: 'Rondônia', 22: 'Roraima', 23: 'Santa Catarina',
               24: 'São Paulo', 25: 'Sergipe', 26: 'Goiás', 27: 'Pernambuco', 28: 'Tocantins'},
    'British Virgin Islands': {1: 'British Virgin Islands'},
    'Canada': {1: 'Canada', 2: 'Ontario', 3: 'Alberta', 4: 'British Columbia', 5: 'Manitoba', 6: 'New Brunswick',
               7: 'Newfoundland', 8: 'Nova Scotia', 9: 'Prince Edward Island', 10: 'Quebec', 11: 'Saskatchewan',
               12: 'Yukon', 13: 'Northwest Territories', 14: 'Nunavut'},
    'Cayman Islands': {1: 'Cayman Islands'},
    'Chile': {1: 'Chile', 2: 'Región Metropolitana', 3: 'Valparaíso', 4: 'Aisén del General Carlos Ibáñez del Campo',
              5: 'Antofagasta', 6: 'Araucanía', 7: 'Atacama', 8: 'Bío-Bío', 9: 'Coquimbo',
              10: "Libertador General Bernardo O'Higgins", 11: 'Los Lagos', 12: 'Magallanes y Antártica Chilena',
              13: 'Maule', 14: 'Tarapacá'},
    'Colombia': {1: 'Colombia', 2: 'Distrito Capital', 3: 'Cundinamarca', 4: 'Amazonas', 5: 'Antioquia', 6: 'Arauca',
                 7: 'Atlántico', 8: 'Bolívar', 9: 'Boyacá', 10: 'Caldas', 11: 'Caquetá', 12: 'Cauca', 13: 'Cesar',
                 14: 'Chocó', 15: 'Córdoba', 16: 'Guaviare', 17: 'Guainía', 18: 'Huila', 19: 'La Guajira',
                 20: 'Magdalena', 21: 'Meta', 22: 'Nariño', 23: 'Norte de Santander', 24: 'Putumayo', 25: 'Quindío',
                 26: 'Risaralda', 27: 'Archipiélago de San Andrés', 28: 'Santander', 29: 'Sucre', 30: 'Tolima',
                 31: 'Valle del Cauca', 32: 'Vaupés', 33: 'Vichada', 34: 'Casanare'},
    'Costa Rica': {1: 'Costa Rica', 2: 'San José', 3: 'Alajuela', 4: 'Cartago', 5: 'Guanacaste', 6: 'Heredia',
                   7: 'Limón', 8: 'Puntaremas'},
    'Dominica': {1: 'Dominica'},
    'Dominican Republic': {1: 'Dominican Republic', 2: 'Distrito Nacional', 3: 'Azua', 4: 'Baoruco', 5: 'Barahona',
                           6: 'Dajabón', 7: 'Duarte', 8: 'Espaillat', 9: 'Independencia', 10: 'La Altagracia',
                           11: 'Elías Piña', 12: 'La Romana', 13: 'María Trinidad Sánchez', 14: 'Monte Cristi',
                           15: 'Pedernales', 16: 'Peravia', 17: 'Puerto Plata', 18: 'Salcedo', 19: 'Samaná',
                           20: 'Sánchez Ramírez', 21: 'San Juan', 22: 'San Pedro de Macorís', 23: 'Santiago',
                           24: 'Santiago Rodríguez', 25: 'Valverde', 26: 'El Seíbo', 27: 'Hato Mayor', 28: 'La Vega',
                           29: 'Monseñor Nouel', 30: 'Monte Plata', 31: 'San Cristóbal'},
    'Ecuador': {1: 'Ecuador', 2: 'Pichincha', 3: 'Galápagos', 4: 'Azuay', 5: 'Bolívar', 6: 'Cañar', 7: 'Carchi',
                8: 'Chimborazo', 9: 'Cotopaxi', 10: 'El Oro', 11: 'Esmeraldas', 12: 'Guayas', 13: 'Imbabura',
                14: 'Loja', 15: 'Los Ríos', 16: 'Manabí', 17: 'Morona-Santiago', 18: 'Pastaza', 19: 'Tungurahua',
                20: 'Zmora-Chinchipe', 21: 'Sucumbios', 22: 'Napo', 23: 'Orellana'},
    'El Salvador': {1: 'El Salvador', 2: 'San Salvador', 3: 'Ahuachapán', 4: 'Cabañas', 5: 'Chalatenango',
                    6: 'Cuscatlán', 7: 'La Libertad', 8: 'La Paz', 9: 'La Unión', 10: 'Morazán', 11: 'San Miguel',
                    12: 'Santa Ana', 13: 'San Vicente', 14: 'Sonsonate', 15: 'Usulután'},
    'French Guiana': {1: 'French Guiana'},
    'Grenada': {1: 'Grenada'},
    'Guadeloupe': {1: 'Guadeloupe'},
    'Guatemala': {1: 'Guatemala', 2: 'Guatemala', 3: 'Alta Verapaz', 4: 'Baja Verapaz', 5: 'Chimaltenango',
                  6: 'Chiquimula', 7: 'El Progreso', 8: 'Escuintla', 9: 'Huehuetenango', 10: 'Izabal', 11: 'Jalapa',
                  12: 'Jutiapa', 13: 'Petén', 14: 'Quetzaltenango', 15: 'Quiché', 16: 'Retalhuleu', 17: 'Sacatepéquez',
                  18: 'San Marcos', 19: 'Santa Rosa', 20: 'Sololá', 21: 'Suchitepéquez', 22: 'Totonicapán',
                  23: 'Zacapa'},
    'Guyana': {1: 'Guyana', 2: 'Demerara-Mahaica', 3: 'Barima-Waini', 4: 'Cuyuni-Mazaruni', 5: 'East Berbice-Corentyne',
               6: 'Essequibo Islands-West Demerara', 7: 'Mahaica-Berbice', 8: 'Pomeroon-Supenaam', 9: 'Potaro-Siparuni',
               10: 'Upper Demerara-Berbice', 11: 'Upper Takutu-Upper Essequibo'},
    'Haiti': {1: 'Haiti', 2: 'Ouest', 3: 'Nord-Ouest', 4: 'Artibonite', 5: 'Centre', 6: "Grand'Anse", 7: 'Nord',
              8: 'Nord-Est', 9: 'Sud', 10: 'Sud-Est'},
    'Honduras': {1: 'Honduras', 2: 'Francisco Morazán', 3: 'Atlántida', 4: 'Choluteca', 5: 'Colón', 6: 'Comayagua',
                 7: 'Copán', 8: 'Cortés', 9: 'El Paraíso', 10: 'Gracias a Dios', 11: 'Intibucá',
                 12: 'Islas de la Bahía', 13: 'La Paz', 14: 'Lempira', 15: 'Ocotepeque', 16: 'Olancho',
                 17: 'Santa Bárbara', 18: 'Valle', 19: 'Yoro'},
    'Jamaica': {1: 'Jamaica', 2: 'Saint Thomas', 3: 'Clarendon', 4: 'Hanover', 5: 'Manchester', 6: 'Portland',
                7: 'Saint Andrew', 8: 'Saint Ann', 9: 'Saint Catherine', 10: 'Saint Elizabeth', 11: 'Saint James',
                12: 'Saint Mary', 13: 'trelawny', 14: 'Westmoreland', 15: 'Kingston-Saint John'},
    'Martinique': {1: 'Martinique'},
    'Mexico': {1: 'Mexico', 2: 'Distrito Federal', 3: 'Aguascalientes', 4: 'Baja California', 5: 'Baja California Sur',
               6: 'Campeche', 7: 'Chiapas', 8: 'Chihuahua', 9: 'Coahuila de Zaragoza', 10: 'Colima', 11: 'Durango',
               12: 'Guanajuato', 13: 'Guerrero', 14: 'Hidalgo', 15: 'Jalisco', 16: 'México', 17: 'Michoacán de Ocampo',
               18: 'Morelos', 19: 'Nayarit', 20: 'Nuevo León', 21: 'Oaxaca', 22: 'Puebla', 23: 'Querétaro de Arteaga',
               24: 'Quintana Roo', 25: 'San Luis Potosí', 26: 'Sinaloa', 27: 'Sonora', 28: 'Tabasco', 29: 'Tamaulipas',
               30: 'Tlaxcala', 31: 'Veracruz-Llave', 32: 'Yucatán', 33: 'Zacatecas'},
    'Montserrat': {1: 'Montserrat'},
    'Netherlands Antilles': {1: 'Netherlands Antilles'},
    'Nicaragua': {1: 'Nicaragua', 2: 'Managua', 3: 'Boaco', 4: 'Carazo', 5: 'Chinandega', 6: 'Chontales', 7: 'Estelí',
                  8: 'Granada', 9: 'Jinotega', 10: 'León', 11: 'Madriz', 12: 'Masaya', 13: 'Matagalpa',
                  14: 'Nueva Segovia', 15: 'Río San Juan', 16: 'Rivas', 17: 'Atlántico Norte', 18: 'Atlántico Sur'},
    'Panama': {1: 'Panama', 2: 'Panamá', 3: 'Bocas del Toro', 4: 'Chiriquí', 5: 'Coclé', 6: 'Colón', 7: 'Darién',
               8: 'Herrera', 9: 'Los Santos', 10: 'San Blas', 11: 'Veraguas'},
    'Paraguay': {1: 'Paraguay', 2: 'Central', 3: 'Alto Paraná', 4: 'Amambay', 5: 'Caaguazú', 6: 'Caazapá',
                 7: 'Concepción', 8: 'Cordillera', 9: 'Guairá', 10: 'Itapúa', 11: 'Misiones', 12: 'Ñeembucú',
                 13: 'Paraguarí', 14: 'Presidente Hayes', 15: 'San Pedro', 16: 'Canindeyú', 17: 'Asunción',
                 18: 'Alto Paraguay', 19: 'Boquerón'},
    'Peru': {1: 'Peru', 2: 'Lima', 3: 'Amazonas', 4: 'Ancash', 5: 'Apurímac', 6: 'Arequipa', 7: 'Ayacucho',
             8: 'Cajamarca', 9: 'Callao', 10: 'Cuzco', 11: 'Huancavelica', 12: 'Huánuco', 13: 'Ica', 14: 'Junín',
             15: 'La Libertad', 16: 'Lambayeque', 17: 'Loreto', 18: 'Madre de Dios', 19: 'Moquegua', 20: 'Pasco',
             21: 'Piura', 22: 'Puno', 23: 'San Martín', 24: 'Tacna', 25: 'Tumbes', 26: 'Ucayali'},
    'St. Kitts and Nevis': {1: 'St. Kitts and Nevis', 2: 'Saint George Basseterre', 3: 'Christ Church Nichola Town',
                            4: 'Saint Anne Sandy Point', 5: 'Saint George Gingerland', 6: 'Saint James Windward',
                            7: 'Saint John Capesterre', 8: 'Saint John Figtree', 9: 'Saint Mary Cayon',
                            10: 'Saint Paul Capesterre', 11: 'Saint Paul Charlestown', 12: 'Saint Peter Basseterre',
                            13: 'Saint Thomas Lowland', 14: 'Saint Thomas Middle Island', 15: 'Trinity Palmetto Point'},
    'St. Lucia': {1: 'St. Lucia'},
    'St. Vincent and the Grenadines': {1: 'St. Vincent and the Grenadines'},
    'Suriname': {1: 'Suriname', 2: 'Paramaribo', 3: 'Brokopondo', 4: 'Commewijne', 5: 'Coronie', 6: 'Marowijne',
                 7: 'Nickerie', 8: 'Para', 9: 'Saramacca', 10: 'Sipaliwini', 11: 'Wanica'},
    'Trinidad and Tobago': {1: 'Trinidad and Tobago', 2: 'Port-of-Spain', 3: 'Arima', 4: 'Caroni', 5: 'Mayaro',
                            6: 'Nariva', 7: 'Saint Andrew', 8: 'Saint David', 9: 'Saint George', 10: 'Saint Patrick',
                            11: 'San Fernando', 12: 'Tobago', 13: 'Victoria'},
    'Turks and Caicos Islands': {1: 'Turks and Caicos Islands'},
    'United States': {1: 'United States', 2: 'District of Columbia', 3: 'Alaska', 4: 'Alabama', 5: 'Arkansas',
                      6: 'Arizona', 7: 'California', 8: 'Colorado', 9: 'Connecticut', 10: 'Delaware', 11: 'Florida',
                      12: 'Georgia', 13: 'Hawaii', 14: 'Iowa', 15: 'Idaho', 16: 'Illinois', 17: 'Indiana', 18: 'Kansas',
                      19: 'Kentucky', 20: 'Louisiana', 21: 'Massachusetts', 22: 'Maryland', 23: 'Maine', 24: 'Michigan',
                      25: 'Minnesota', 26: 'Missouri', 27: 'Mississippi', 28: 'Montana', 29: 'North Carolina',
                      30: 'North Dakota', 31: 'Nebraska', 32: 'New Hampshire', 33: 'New Jersey', 34: 'New Mexico',
                      35: 'Nevada', 36: 'New York', 37: 'Ohio', 38: 'Oklahoma', 39: 'Oregon', 40: 'Pennsylvania',
                      41: 'Rhode Island', 42: 'South Carolina', 43: 'South Dakota', 44: 'Tennessee', 45: 'Texas',
                      46: 'Utah', 47: 'Virginia', 48: 'Vermont', 49: 'Washington', 50: 'Wisconsin', 51: 'West Virginia',
                      52: 'Wyoming', 53: 'Puerto Rico'},
    'Uruguay': {1: 'Uruguay', 2: 'Montevideo', 3: 'Artigas', 4: 'Canelones', 5: 'Cerro Largo', 6: 'Colonia',
                7: 'Durazno', 8: 'Flores', 9: 'Florida', 10: 'Lavalleja', 11: 'Maldonado', 12: 'Paysandú',
                13: 'Río Negro', 14: 'Rivera', 15: 'Rocha', 16: 'Salto', 17: 'San José', 18: 'Soriano',
                19: 'Tacuarembó', 20: 'Treinta y Tres'},
    'US Virgin Islands': {1: 'US Virgin Islands'},
    'Venezuela': {1: 'Venezuela', 2: 'Distrito Federal', 3: 'Amazonas', 4: 'Anzoátegui', 5: 'Apure', 6: 'Aragua',
                  7: 'Barinas', 8: 'Bolívar', 9: 'Carabobo', 10: 'Cojedes', 11: 'Delta Amacuro', 12: 'Falcón',
                  13: 'Guárico', 14: 'Lara', 15: 'Mérida', 16: 'Miranda', 17: 'Monagas', 18: 'Nueva Esparta',
                  19: 'Portuguesa', 20: 'Sucre', 21: 'Táchira', 22: 'Trujillo', 23: 'Yaracuy', 24: 'Zulia',
                  25: 'Dependencias Federales', 26: 'Vargas'},
    'Albania': {1: 'Albania', 2: 'Tirana', 3: 'Berat', 4: 'Dibër', 5: 'Durrës', 6: 'Elbasan', 7: 'Fier',
                8: 'Gjirokastër', 9: 'Korcë', 10: 'Kukës', 11: 'Lezhë', 12: 'Shkodër', 13: 'Vlorë'},
    'Australia': {1: 'Australia', 2: 'Australian Capital Territory', 3: 'New South Wales', 4: 'Northern Territory',
                  5: 'Queensland', 6: 'South Australia', 7: 'Tasmania', 8: 'Victoria', 9: 'Western Australia'},
    'Austria': {1: 'Austria', 2: 'Vienna', 3: 'Burgenland', 4: 'Carinthia', 5: 'Lower Austria', 6: 'Upper Austria',
                7: 'Salzburg', 8: 'Styria', 9: 'Tyrol', 10: 'Vorarlberg'},
    'Belgium': {1: 'Belgium', 2: 'Brussels Region', 3: 'Flanders', 4: 'Wallonia'},
    'Bosnia & Herzegovina': {1: 'Bosnia & Herzegovina', 2: 'Fed. of Bosnia and Herzegovina', 3: 'Republika Srpska',
                             4: 'Brcko Distrikt'},
    'Botswana': {1: 'Botswana', 2: 'South-East', 3: 'Central', 4: 'Ghanzi', 5: 'Kgalagadi', 6: 'Kgatleng', 7: 'Kweneng',
                 8: 'North-East', 9: 'North-West', 10: 'Southern'},
    'Bulgaria': {1: 'Bugaria', 2: 'Sofia City', 3: 'Sofia Province', 4: 'Blagoevgrad', 5: 'Pleven', 6: 'Vidin',
                 7: 'Varna', 8: 'Burgas', 9: 'Dobric', 10: 'Gabrovo', 11: 'Haskovo', 12: 'Yambol', 13: 'Kardzhali',
                 14: 'Kyustendil', 15: 'Lovech', 16: 'Montana', 17: 'Pazardzhik', 18: 'Pernik', 19: 'Plovdiv',
                 20: 'Razgrad', 21: 'Ruse', 22: 'Silistra', 23: 'Sliven', 24: 'Smolyan', 25: 'Stara Zagora',
                 26: 'Shumen', 27: 'Targovishte', 28: 'Veliko Tarnovo', 29: 'Vratsa'},
    'Croatia': {1: 'Croatia', 2: 'Zagreb Region', 3: 'Central Croatia', 4: 'Adriatic Croatia', 5: 'East Croatia'},
    'Cyprus': {1: 'Cyprus', 2: 'Nicosia', 3: 'Famagusta', 4: 'Kyrenia', 5: 'Larnaca', 6: 'Limassol', 7: 'Paphos'},
    'Czech Republic': {1: 'Czech Republic', 2: 'Prague', 3: 'Central Bohemian Region', 4: 'South Bohemian Region',
                       5: 'Plzen Region', 6: 'Karlovy Vary Region', 7: 'Ústi nad Labem Region', 8: 'Liberec Region',
                       9: 'Hradec Králové Region', 10: 'Pardubice Region', 11: 'Olomouc Region',
                       12: 'Moravian-Silesian Region', 13: 'South Moravian Region', 14: 'Zlín Region',
                       15: 'Vysocina Region'},
    'Denmark': {1: 'Denmark', 2: 'Copenhagen', 3: 'Frederiksberg', 4: 'Copenhagen County', 5: 'Frederiksborg',
                6: 'Roskilde', 7: 'West Zealand', 8: 'Storstrøm', 9: 'Funen', 10: 'South Jutland', 11: 'Ribe',
                12: 'Vejle', 13: 'Ringkjøbing', 14: 'Viborg', 15: 'North Jutland', 16: 'Århus', 17: 'Bornholm',
                18: 'Greenland'},
    'Estonia': {1: 'Estonia', 2: 'Harju', 3: 'Hiiu', 4: 'Ida-Viru', 5: 'Jõgeva', 6: 'Järva', 7: 'Lääne',
                8: 'Lääne-Viru', 9: 'Põlva', 10: 'Pärnu', 11: 'Rapla', 12: 'Saare', 13: 'Tartu', 14: 'Valga',
                15: 'Viljandi', 16: 'Võru'},
    'Finland': {1: 'Finland', 2: 'Southern Finland', 3: 'Western Finland', 4: 'Eastern Finland', 5: 'Province of Oulu',
                6: 'Lapland', 7: 'Åland'},
    'France': {1: 'France', 2: 'Île-de-France', 3: 'Alsace', 4: 'Aquitaine', 5: 'Auvergne', 6: 'Lower Normandy',
               7: 'Burgundy', 8: 'Brittany', 9: 'Centre Loire Valley', 10: 'Champagne-Ardenne', 11: 'Corsica',
               12: 'Franche-Comté', 13: 'Upper Normandy', 14: 'Languedoc-Roussillon', 15: 'Limousin', 16: 'Lorraine',
               17: 'Midi-Pyrénées', 18: 'Nord-Pas-de-Calais', 19: 'Western Loire Valley', 20: 'Picardy',
               21: 'Poitou-Charentes', 22: 'Provence', 23: "Provence-Alpes-Côte d'Azur", 24: 'Rhône-Alpes',
               25: 'Guadeloupe', 26: 'Martinique', 27: 'French Guiana', 28: 'Réunion'},
    'Germany': {1: 'Germany', 2: 'Berlin', 3: 'Hesse', 4: 'Baden-Württemberg', 5: 'Bavaria', 6: 'Brandenburg',
                7: 'Bremen', 8: 'Hamburg', 9: 'Mecklenburg-Western Pomerania', 10: 'Lower Saxony',
                11: 'North Rhine-Westphalia', 12: 'Rhineland-Palatinate', 13: 'Saarland', 14: 'Saxony',
                15: 'Saxony-Anhalt', 16: 'Schleswig-Holstein', 17: 'Thuringia'},
    'Greece': {1: 'Greece', 2: 'Attica', 3: 'Central Greece', 4: 'Central Macedonia', 5: 'Crete',
               6: 'East Macedonia and Thrace', 7: 'Epirus', 8: 'Ionian Islands', 9: 'North Aegean', 10: 'Peloponnese',
               11: 'South Aegean', 12: 'Thessaly', 13: 'West Greece', 14: 'West Macedonia'},
    'Hungary': {1: 'Hungary', 2: 'Budapest', 3: 'Bács-Kiskun', 4: 'Baranya', 5: 'Békés', 6: 'Borsod-Abaúj-Zemplén',
                7: 'Csongrád', 8: 'Fejér', 9: 'Gyor-Moson-Sopron', 10: 'Hajdú-Bihar', 11: 'Heves',
                12: 'Jász-Nagykun-Szolnok', 13: 'Komárom-Esztergom', 14: 'Nógrád', 15: 'Pest', 16: 'Somogy',
                17: 'Szabolcs-Szatmár-Bereg', 18: 'Tolna', 19: 'Vas', 20: 'Veszprém', 21: 'Zala'},
    'Iceland': {1: 'Iceland', 2: 'Capital Region', 3: ' Eastland', 4: 'Northland East', 5: 'Northland West',
                6: 'Southland', 7: 'Southern Peninsula', 8: 'Western Fjords', 9: 'Westland'},
    'Ireland': {1: 'Ireland', 2: 'Dublin', 3: 'Border', 4: 'West', 5: 'Midland', 6: 'Mid-East', 7: 'Mid-West',
                8: 'South-East', 9: 'South-West'},
    'Italy': {1: 'Italy', 2: 'Lazio', 3: 'Aosta Valley', 4: 'Piedmont', 5: 'Liguria', 6: 'Lombardy',
              7: 'Trentino-South Tyrol', 8: 'Veneto', 9: 'Friuli Venezia Giulia', 10: 'Emilia-Romagna', 11: 'Tuscany',
              12: 'Umbria', 13: 'Marche', 14: 'Abruzzo', 15: 'Molise', 16: 'Campania', 17: 'Apulia', 18: 'Basilicata',
              19: 'Calabria', 20: 'Sicily', 21: 'Sardinia'},
    'Latvia': {1: 'Latvia', 2: 'Riga', 3: 'Kuldiga', 4: 'Liepaja', 5: 'Talsi', 6: 'Ventspils', 7: 'Saldus', 8: 'Tukums',
               9: 'Aizkraukle', 10: 'Aluksne', 11: 'Cesis', 12: 'Gulbene', 13: 'Madona', 14: 'Limbazi', 15: 'Ogre',
               16: 'Valka', 17: 'Valmiera', 18: 'Balvi', 19: 'Daugavpils', 20: 'Jekabpils', 21: 'Kraslava', 22: 'Ludza',
               23: 'Preili', 24: 'Rezekne', 25: 'Bauska', 26: 'Dobele', 27: 'Jelgava'},
    'Lesotho': {1: 'Lesotho', 2: 'Maseru', 3: 'Berea', 4: 'Butha-Buthe', 5: 'Leribe', 6: 'Mafeteng', 7: "Mohale's Hoek",
                8: 'Mokhotlong', 9: "Qacha's Nek", 10: 'Quthing', 11: 'Thaba-Tseka'},
    'Liechtenstein': {1: 'Liechtenstein', 2: 'Upper Country', 3: 'Lower Country'},
    'Lithuania': {1: 'Lithuania', 2: 'Vilnius', 3: 'Alytus', 4: 'Kaunas', 5: 'Klaipeda', 6: 'Marijampole',
                  7: 'Panevezys', 8: 'Šiauliai', 9: 'Taurage', 10: 'Telšiai', 11: 'Utena'},
    'Luxembourg': {1: 'Luxembourg', 2: 'Luxembourg', 3: 'Diekirch', 4: 'Grevenmacher'},
    'F.Y.R. of Macedonia': {1: 'F.Y.R. of Macedonia', 2: 'Skopje', 3: 'Eastern', 4: 'Northeastern', 5: 'Pelagonia',
                            6: 'Polog', 7: 'Southeastern', 8: 'Southwestern', 9: 'Vardar'},
    'Malta': {1: 'Malta', 2: 'Malta', 3: 'Gozo and Comino'},
    'Montenegro': {1: 'Montenegro', 2: 'Podgorica', 3: 'Andrijevica', 4: 'Bar', 5: 'Berane', 6: 'Bijelo Polje',
                   7: 'Budva', 8: 'Cetinje', 9: 'Danilovgrad', 10: 'Herceg Novi', 11: 'Kolasin', 12: 'Kotor',
                   13: 'Mojkovac', 14: 'Niksic', 15: 'Plav', 16: 'Plužine', 17: 'Pljevlja', 18: 'Rozaje', 19: 'Šavnik',
                   20: 'Tivat', 21: 'Ulcinj', 22: 'Zabljak'},
    'Mozambique': {1: 'Mozambique', 2: 'Maputo (City)', 3: 'Maputo (Province)', 4: 'Cabo Delgado', 5: 'Gaza',
                   6: 'Inhambane', 7: 'Manica', 8: 'Nampula', 9: 'Niassa', 10: 'Sofala', 11: 'Tete', 12: 'Zambezia'},
    'Namibia': {1: 'Namibia', 2: 'Khomas', 3: 'Caprivi', 4: 'Erongo', 5: 'Hardap', 6: 'Karas', 7: 'Okavango',
                8: 'Kunene', 9: 'Ohangwena', 10: 'Omaheke', 11: 'Omusati', 12: 'Oshana', 13: 'Oshikoto',
                14: 'Otjozondjupa'},
    'Netherlands': {1: 'Netherlands', 2: 'North Holland', 3: 'Drenthe', 4: 'Flevoland', 5: 'Friesland', 6: 'Gelderland',
                    7: 'Groningen', 8: 'Limburg', 9: 'North Brabant', 10: 'Overijssel', 11: 'South Holland',
                    12: 'Utrecht', 13: 'Zeeland'},
    'New Zealand': {1: 'New Zealand', 2: 'Wellington', 3: 'Auckland', 4: 'Bay of Plenty', 5: 'Canterbury', 6: 'Otago',
                    7: "Hawke's Bay", 8: 'Manawatu-Wanganui', 9: 'Nelson', 10: 'Northland', 11: 'Rotorua',
                    12: 'Southland', 13: 'Taranaki', 14: 'Waikato'},
    'Norway': {1: 'Norway', 2: 'Østlandet', 3: 'Nord-Norge', 4: 'Trøndelag', 5: 'Vestlandet', 6: 'Sørlandet'},
    'Poland': {1: 'Poland', 2: 'Masovia', 3: 'Lower Silesia', 4: 'Kuyavia-Pomerania', 5: 'Lodz', 6: 'Lublin',
               7: 'Lubusz', 8: 'Lesser Poland', 9: 'Opole', 10: 'Subcarpathia', 11: 'Podlasie', 12: 'Pomerania',
               13: 'Silesia', 14: 'Swietokrzyskie', 15: 'Warmia-Masuria', 16: 'Greater Poland',
               17: 'Western Pomerania'},
    'Portugal': {1: 'Portugal', 2: 'Lisbon', 3: 'Alentejo', 4: 'Algarve', 5: 'Centro', 6: 'Norte', 7: 'Madeira',
                 8: 'Azores'},
    'Romania': {1: 'Romania', 2: 'Bucharest', 3: 'Alba', 4: 'Arad', 5: 'Arges', 6: 'Bacau', 7: 'Bihor',
                8: 'Bistrita-Nasaud', 9: 'Botosani', 10: 'Braila', 11: 'Brasov', 12: 'Buzau', 13: 'Calarasi',
                14: 'Caras-Severin', 15: 'Cluj', 16: 'Constanta', 17: 'Covasna', 18: 'Dâmbovita', 19: 'Dolj',
                20: 'Galati', 21: 'Giurgiu', 22: 'Gorj', 23: 'Harghita', 24: 'Hunedoara', 25: 'Ialomita', 26: 'Iasi',
                27: 'Ilfov', 28: 'Maramures', 29: 'Mehedinti', 30: 'Mures', 31: 'Neamt', 32: 'Olt', 33: 'Prahova',
                34: 'Salaj', 35: 'Satu Mare', 36: 'Sibiu', 37: 'Suceava', 38: 'Teleorman', 39: 'Timis', 40: 'Tulcea',
                41: 'Vâlcea', 42: 'Vaslui', 43: 'Vrancea'},
    'Russia': {1: 'Russia', 2: 'Central Federal District', 3: 'Far Eastern Federal District',
               4: 'Northwestern Federal District', 5: 'Siberian Federal District', 6: 'Southern Federal District',
               7: 'Urals Federal District', 8: 'Volga Federal District'},
    'Serbia': {1: 'Serbia', 2: 'Central Serbia', 3: 'Vojvodina', 4: 'Kosovo & Metohija'},
    'Slovakia': {1: 'Slovakia', 2: 'Bratislava', 3: 'Basnká Bystrica', 4: 'Košice', 5: 'Nitra', 6: 'Prešov',
                 7: 'Trencín', 8: 'Trnava', 9: 'Žilina'},
    'Slovenia': {1: 'Slovenia', 2: 'Carniola', 3: 'Lower Styria', 4: 'Prekmurje', 5: 'Slovenian Littoral',
                 6: 'Carinthia'},
    'South Africa': {1: 'South Africa', 2: 'Gautneg', 3: 'Western Cape', 4: 'Northern Cape', 5: 'Eastern Cape',
                     6: 'KwaZulu-Natal', 7: 'Free State', 8: 'Morth West', 9: 'Mpumalanga', 10: 'Limpopo'},
    'Spain': {1: 'Spain', 2: 'Madrid', 3: 'Andalusia', 4: 'Aragon', 5: 'Principality of Asturias',
              6: 'Balearic Islands', 7: 'Canary Islands', 8: 'Cantabria', 9: 'Castile-La Mancha', 10: 'Castilla y León',
              11: 'Catalonia', 12: 'Valencia', 13: 'Extremadura', 14: 'Galicia', 15: 'Murcia', 16: 'Navarre',
              17: 'Basque Country', 18: 'La Rioja'},
    'Swaziland': {1: 'Swaziland', 2: 'Hhohho', 3: 'Lubombo', 4: 'Manzini', 5: 'Shiselweni'},
    'Sweden': {1: 'Sweden', 2: 'Stockholm County', 3: 'Skåne County', 4: 'Västra Götaland County',
               5: 'Östergötland County', 6: 'Södermanland County', 7: 'Värmland County', 8: 'Uppsala County',
               9: 'Gävleborg County', 10: 'Västerbotten County', 11: 'Norrbotten County', 12: 'Gotland Island',
               13: 'Jämtland County', 14: 'Dalarna County', 15: 'Blekinge County', 16: 'Örebro County',
               17: 'Västernorrland County', 18: 'Jönköping County', 19: 'Kronoberg County', 20: 'Kalmar County',
               21: 'Västmanland County', 22: 'Halland County'},
    'Switzerland': {1: 'Switzerland', 2: 'Bern', 3: 'Appenzell', 4: 'Aargau', 5: 'Basel-City', 6: 'Fribourg',
                    7: 'Geneva', 8: 'Glarus', 9: 'Graubünden', 10: 'Jura', 11: 'Luzern', 12: 'Neuchâtel',
                    13: 'Obwalden', 14: 'St. Gallen', 15: 'Schaffhausen', 16: 'Schwyz', 17: 'Solothurn', 18: 'Thurgau',
                    19: 'Ticino', 20: 'Uri', 21: 'Valais', 22: 'Vaud', 23: 'Zug', 24: 'Zürich'},
    'Turkey': {1: 'Turkey', 2: 'Ankara', 3: 'Istanbul', 4: 'Izmir', 5: 'Bursa', 6: 'Adana', 7: 'Gaziantep', 8: 'Konya',
               9: 'Antalya', 10: 'Diyarbakir', 11: 'Mersin', 12: 'Kayseri', 13: 'Eskisehir', 14: 'Sanliurfa',
               15: 'Malatya', 16: 'Erzurum', 17: 'Samsun', 18: 'Van', 19: 'Kahramanmaras', 20: 'Denizli', 21: 'Batman',
               22: 'Elazig', 23: 'Sakarya', 24: 'Kocaeli', 25: 'Sivas', 26: 'Manisa', 27: 'Trabzon', 28: 'Balikesir',
               29: 'Adiyaman', 30: 'Tekirdag', 31: 'Kirikkale', 32: 'Osmaniye', 33: 'Kütahya', 34: 'Corum',
               35: 'Isparta', 36: 'Aydin', 37: 'Hatay', 38: 'Mardin', 39: 'Aksaray', 40: 'Afyonkarahisar', 41: 'Tokat',
               42: 'Edirne', 43: 'Karaman', 44: 'Ordu', 45: 'Siirt', 46: 'Erzincan', 47: 'Cankiri', 48: 'Zonguldak',
               49: 'Yozgat', 50: 'Usak'},
    'United Kingdom': {1: 'United Kingdom', 2: 'England', 3: 'Isle of Man', 4: 'Scotland', 5: 'Wales',
                       6: 'Northern Ireland'},
    'Zambia': {1: 'Zambia', 2: 'Lusaka Province', 3: 'Central Province', 4: 'Copperbelt Province',
               5: 'Eastern Province', 6: 'Luapula Province', 7: 'Northern Province', 8: 'North-Western Province',
               9: 'Southern Province', 10: 'Western Province'},
    'Zimbabwe': {1: 'Zimbabwe', 2: 'Harare', 3: 'Bulawayo', 4: 'Manicaland', 5: 'Mashonaland Central',
                 6: 'Mashonaland East', 7: 'Mashonaland West', 8: 'Masvingo', 9: 'Matabeleland North',
                 10: 'Matabeleland South', 11: 'Midlands'},
    'Azerbaijan': {1: 'Azerbaijan'},
    'Mauritania': {1: 'Mauritania'},
    'Mali': {1: 'Mali'},
    'Niger': {1: 'Niger'},
    'Chad': {1: 'Chad'},
    'Sudan': {1: 'Sudan'},
    'Eritrea': {1: 'Eritrea'},
    'Djibouti': {1: 'Djibouti'},
    'Somalia': {1: 'Somalia'},
    'Taiwan': {1: 'Taiwan', 2: 'Taipei City', 3: 'Kaohsiung City', 4: 'Keelung City', 5: 'Hsinchu City',
               6: 'Taichung City', 7: 'Chiayi City', 8: 'Tainan City', 9: 'Taipei county', 10: 'Taoyuan County',
               11: 'HsinChu County', 12: 'Miaoli County', 13: 'Taichung County', 14: 'Changhua County',
               15: 'Nantou County', 16: 'Yunlin County', 17: 'Chiayi County', 18: 'Tainan County',
               19: 'Kaohsiung County', 20: 'Pingtung County', 21: 'Yilan County', 22: 'Hualien County',
               23: 'Taitung County', 24: 'Penghu County', 25: 'Kinmen County', 26: 'Lienchiang County'},
    'South Korea': {1: 'South Korea', 2: 'Seoul-teukbyeolsi', 3: 'Busan-gwangyeoksi', 4: 'Daegu-gwangyeoksi',
                    5: 'Incheon-gwangyeoksi', 6: 'Gwangju-gwangyeoksi', 7: 'Daejeon-gwangyeoksi',
                    8: 'Ulsan-gwangyeoksi', 9: 'Gyeonggi-do', 10: 'Gangwon-do', 11: 'Chungcheongbuk-do',
                    12: 'Chungcheongnam-do', 13: 'Jeollabuk-do', 14: 'Jeollanam-do', 15: 'Gyeongsangbuk-do',
                    16: 'Gyeongsangnam-do', 17: 'Jeju-teukbyeoljachido'},
    'Hong Kong': {1: 'Hong Kong'},
    'Macao': {1: 'Macao'},
    'Indonesia': {1: 'Indonesia', 2: 'Jakarta Raya', 3: 'Aceh', 4: 'Bali', 5: 'Bengkulu', 6: 'Jambi', 7: 'Central Java',
                  8: 'East Java', 9: 'Papua', 10: 'Yogyakarta', 11: 'West Kalimantan', 12: 'South Kalimantan',
                  13: 'Kalimantan Tengah', 14: 'Kalimantan Timur', 15: 'Lampung', 16: 'Nusa Tenggara Barat',
                  17: 'East Nusa Tenggara', 18: 'Riau', 19: 'Sulawesi Selatan', 20: 'Sulawesi Tengah',
                  21: 'Sulawesi Tenggara', 22: 'West Sumatra', 23: 'North Sumatra', 24: 'Maluku', 25: 'Maluku Utara',
                  26: 'Jawa Barat', 27: 'Sulawesi Utara', 28: 'Sumatera Selatan', 29: 'Banten', 30: 'Gorontalo',
                  31: 'Kepulauan Bangka Belitung', 32: 'Irian Jaya Barat', 33: 'Kepulauan Riau', 34: 'Sulawesi Barat'},
    'Singapore': {1: 'Singapore'},
    'Thailand': {1: 'Thailand', 2: 'Krung Thep Mahanakhon', 3: 'Mae Hong Son', 4: 'Chiang Mai', 5: 'Chiang Rai',
                 6: 'Nan', 7: 'Lamphun', 8: 'Lampang', 9: 'Phrae', 10: 'Tak', 11: 'Sukhothai', 12: 'Uttaradit',
                 13: 'Kamphaeng Phet', 14: 'Phitsanulok', 15: 'Phichit', 16: 'Phetchabun', 17: 'Uthai Thani',
                 18: 'Nakhon Sawan', 19: 'Nong Khai', 20: 'Loei', 21: 'Sakon Nakhon', 22: 'Khon Kaen', 23: 'Kalasin',
                 24: 'Maha Sarakham', 25: 'Roi Et', 26: 'Chaiyaphum', 27: 'Nakhon Ratchasima', 28: 'Buriram',
                 29: 'Surin', 30: 'Sisaket', 31: 'Narathiwat', 32: 'Chai Nat', 33: 'Sing Buri', 34: 'Lop Buri',
                 35: 'Ang Thong', 36: 'Phra Nakhon Si Ayutthaya', 37: 'Sara Buri', 38: 'Nonthaburi', 39: 'Pathum Thani',
                 40: 'Phayao', 41: 'Samut Prakan', 42: 'Nakhon Nayok', 43: 'Chachoengsao', 44: 'Chon Buri',
                 45: 'Rayong', 46: 'Chanthaburi', 47: 'Trat', 48: 'Kanchanaburi', 49: 'Suphan Buri', 50: 'Ratchaburi',
                 51: 'Nakhon Pathom', 52: 'Samut Songkhram', 53: 'Samut Sakhon', 54: 'Phetchaburi',
                 55: 'Prachuap Khiri Khan', 56: 'Chumphon', 57: 'Ranong', 58: 'Surat Thani', 59: 'Phangnga',
                 60: 'Phuket', 61: 'Krabi', 62: 'Nakhon Si Thammarat', 63: 'Trang', 64: 'Phatthalung', 65: 'Satun',
                 66: 'Songkhla', 67: 'Pattani', 68: 'Yala', 69: 'Yasothon', 70: 'Nakhon Phanom', 71: 'Prachin Buri',
                 72: 'Ubon Ratchathani', 73: 'Udon Thani', 74: 'Amnat Charoen', 75: 'Mukdahan', 76: 'Nong Bua Lamphu',
                 77: 'Sa Kaeo'},
    'Philippines': {1: 'Philippines', 2: 'Manila', 3: 'Autonomous Region in Muslim Mindanao', 4: 'Bicol', 5: 'Cagayan',
                    6: 'Calabarzon', 7: 'Caraga', 8: 'Central Luzon', 9: 'Central Visayas', 10: 'Cordillera',
                    11: 'Davao', 12: 'Eastern Visayas', 13: 'Ilocos', 14: 'Mimaro', 15: 'Mindanao',
                    16: 'Northern Mindanao', 17: 'Soccsksargen', 18: 'Western Visayas', 19: 'Zamboanga Peninsula'},
    'Malaysia': {1: 'Malaysia', 2: 'Kuala Lumpur', 3: 'Johor', 4: 'Kedah', 5: 'Kelantan', 6: 'Melaka',
                 7: 'Negeri Sembilan', 8: 'Pahang', 9: 'Perak', 10: 'Perlis', 11: 'Penang', 12: 'Sarawak',
                 13: 'Selangor', 14: 'Terengganu', 15: 'Labuan', 16: 'Sabah', 17: 'Putrajaya'},
    'China': {1: 'China', 2: 'Beijing', 3: 'Chonqing', 4: 'Shanghai', 5: 'Tianjin', 6: 'Anhui', 7: 'Fujian', 8: 'Gansu',
              9: 'Guangdong', 10: 'Guizhou', 11: 'Hainan', 12: 'Hebei', 13: 'Heilongjiang', 14: 'Henan', 15: 'Hubei',
              16: 'Húnán', 17: 'Jiangsu', 18: 'Jiangxi', 19: 'Jilin', 20: 'Liaoning', 21: 'Qinghai', 22: 'Shanxi',
              23: 'Shandong', 24: 'Shanxi', 25: 'Sichuan', 26: 'Yunnan', 27: 'Zhejiang', 29: 'Guangxi-Zhuangzu',
              30: 'Nei-Menggu', 31: 'Ningxia-huizu', 32: "Xinjiang-Weiwu'er-zu", 33: 'Xizang'},
    'U.A.E': {1: 'U.A.E', 2: 'Abu Dhabi', 3: 'Ajman', 4: 'Ash Shariqah', 5: 'Ras al-Khaimah', 6: 'Dubai',
              7: 'Al Fujayrah', 8: 'Umm al Qaywayn'},
    'India': {1: 'India', 2: 'Delhi', 3: 'Andaman and Nicobar Islands', 4: 'Andhra Pradesh', 5: 'Assam',
              6: 'Chandigarh', 7: 'Dadra and Nagar Haveli', 8: 'Gujarat', 9: 'Haryana', 10: 'Himachal Pradesh',
              11: 'Kerala', 12: 'Lakshadweep', 13: 'Maharashtra', 14: 'Manipur', 15: 'Meghalaya', 16: 'Karnataka',
              17: 'Nagaland', 18: 'Odisha', 19: 'Puducherry', 20: 'Punjab', 21: 'Rajasthan', 22: 'Tamil Nadu',
              23: 'Tripura', 24: 'West Bengal', 25: 'Other', 26: 'Mizoram', 27: 'Daman and Diu', 28: 'Goa', 29: 'Bihar',
              30: 'Madhya Pradesh', 31: 'Uttar Pradesh', 32: 'Chhattisgarh', 33: 'Jharkhand', 34: 'Uttarakhand'},
    'Egypt': {1: 'Egypt', 2: 'Al Qahirah', 3: 'Ad Daqahliyah', 4: 'Al Bahr al Ahmar', 5: 'Al Buhayrah', 6: 'Al Fayyum',
              7: 'Al Gharbiyah', 8: 'Al Iskandariyah', 9: 'Al Isma‘iliyah', 10: 'Al Jizah', 11: 'Al Minufiyah',
              12: 'Al Minya', 13: 'Al Qalyubiyah', 14: 'Al Wadi al Jadid', 15: 'Ash Sharqiyah', 16: 'As Suways',
              17: 'Aswan', 18: 'Asyut', 19: 'Bani Suwayf', 20: 'Bur Sa‘id', 21: 'Dumyat', 22: 'Kafr ash Shaykh',
              23: 'Matruh', 24: 'Qina', 25: 'Suhaj', 26: "Janub Sina'", 27: "Shamal Sina'", 28: 'Luxor'},
    'Oman': {1: 'Oman', 2: 'Masqat', 3: 'Ad Dakhiliyah', 4: 'Al Batinah', 5: 'Al Wusta', 6: 'Ash Sharqiyah',
             7: 'Az Zahirah', 8: 'Musandam', 9: 'Zufar'},
    'Qatar': {1: 'Qatar'},
    'Kuwait': {1: 'Kuwait'},
    "Saudi Arabia": {1: 'Saudi Arabia', 2: 'Ar Riyad', 3: 'Al Bahah', 4: 'Al Madinah', 5: 'Ash Sharqiyah',
                     6: 'Al Qasim', 7: 'Asir', 8: "Ha'il", 9: 'Makkah', 10: 'Al Hudud ash Shamaliyah', 11: 'Najran',
                     12: 'Jizan', 13: 'Tabuk', 14: 'Al Jawf'},
    "Syria": {1: 'Syria', 2: 'Rif Dimashq', 3: 'Al Hasakah', 4: 'Al Ladhiqiyah', 5: 'Al Qunaytirah', 6: 'Ar Raqqah',
              7: "As Suwayda'", 8: 'Dar‘a', 9: 'Dayr az Zawr', 10: 'Rif Dimashq', 11: 'Halab', 12: 'Hamah', 13: 'Hims',
              14: 'Idlib', 15: 'Tartus'},
    "Bahrain": {1: 'Bahrain'},
    "Jordan": {1: 'Jordan'},
    }
