track_ids = {
    8: "Luigi Circuit",
    1: "Moo Moo Meadows",
    2: "Mushroom Gorge",
    4: "Toad's Factory",
    0: "Mario Cricuit",
    5: "Coconut Mall",
    6: "DK Summit",
    7: "Wario's Gold Mine",
    9: "Daisy Circuit",
    15: "Koopa Cape",
    11: "Maple Treeway",
    3: "Grumble Volcano",
    14: "Dry Dry Ruins",
    10: "Moonview Highway",
    12: "Bowser's Castle",
    13: "Rainbow Road",
    16: "GCN Peach Beach",
    20: "DS Yoshi Falls",
    25: "SNES Ghost Valley 2",
    26: "N64 Mario Raceway",
    27: "N64 Sherbet Land",
    31: "GBA Shy Guy Beach",
    23: "DS Delfino Square",
    18: "GCN Waluigi Stadium",
    21: "DS Desert Hills",
    30: "GBA Bowser Castle 3",
    29: "N64 DK's Jungle Parkway",
    17: "GCN Mario Circuit",
    24: "SNES Mario Circuit 3",
    22: "DS Peach Gardens",
    19: "GCN DK Mountain",
    28: "N64 Bowser's Castle"
}

character_ids = {
    0: "Mario",
    1: "Baby Peach",
    2: "Waluigi",
    3: "Bowser",
    4: "Baby Daisy",
    5: "Dry Bones",
    6: "Baby Mario",
    7: "Luigi",
    8: "Toad",
    9: "Donkey Kong",
    10: "Yoshi",
    11: "Wario",
    12: "Baby Luigi",
    13: "Toadette",
    14: "Koopa Troopa",
    15: "Daisy",
    16: "Peach",
    17: "Birdo",
    18: "Diddy Kong",
    19: "King Boo",
    20: "Bowser Jr.",
    21: "Dry Bowser",
    22: "Funky Kong",
    23: "Rosalina",
    24: "Small Mii Outfit A (Male)",
    25: "Small Mii Outfit A (Female)",
    26: "Small Mii Outfit B (Male)",
    27: "Small Mii Outfit B (Female)",
    28: "Small Mii Outfit C (Male)",
    29: "Small Mii Outfit C (Female)",
    30: "Medium Mii Outfit A (Male)",
    31: "Medium Mii Outfit A (Female)",
    32: "Medium Mii Outfit B (Male)",
    33: "Medium Mii Outfit B (Female)",
    34: "Medium Mii Outfit C (Male)",
    35: "Medium Mii Outfit C (Female)",
    36: "Large Mii Outfit A (Male)",
    37: "Large Mii Outfit A (Female)",
    38: "Large Mii Outfit B (Male)",
    39: "Large Mii Outfit B (Female)",
    40: "Large Mii Outfit C (Male)",
    41: "Large Mii Outfit C (Female)",
    42: "Medium Mii",
    43: "Small Mii",
    44: "Large Mii",
    45: "Peach Biker Outfit",
    46: "Daisy Biker Outfit",
    47: "Rosalina Biker Outfit"
}

vehicle_ids = {
    0: "Standard Kart S",
    1: "Standard Kart M",
    2: "Standard Kart L",
    3: "Booster Seat",
    4: "Classic Dragster",
    5: "Offroader",
    6: "Mini Beast",
    7: "Wild Wing",
    8: "Flame Flyer",
    9: "Cheep Charger",
    10: "Super Blooper",
    11: "Piranha Prowler",
    12: "Tiny Titan",
    13: "Daytripper",
    14: "Jetsetter",
    15: "Blue Falcon",
    16: "Sprinter",
    17: "Honeycoupe",
    18: "Standard Bike S",
    19: "Standard Bike M",
    20: "Standard Bike L",
    21: "Bullet Bike",
    22: "Mach Bike",
    23: "Flame Runner",
    24: "Bit Bike",
    25: "Sugar Scoot",
    26: "Wario Bike",
    27: "Quacker",
    28: "Zip Zip",
    29: "Shooting Star",
    30: "Magikruser",
    31: "Sneakster",
    32: "Spear",
    33: "Jet Bubble",
    34: "Dolphin Dasher",
    35: "Phantom"
}

ghost_type = {
    1: "Player's Best Time",
    2: "World Record Ghost",
    3: "Continental Record Ghost",
    4: "Flag Challenge Ghost",
    6: "Ghost Race",
    7: "Friend Ghost 01",
    8: "Friend Ghost 02",
    9: "Friend Ghost 03",
    10: "Friend Ghost 04",
    11: "Friend Ghost 05",
    12: "Friend Ghost 06",
    13: "Friend Ghost 07",
    14: "Friend Ghost 08",
    15: "Friend Ghost 09",
    16: "Friend Ghost 10",
    17: "Friend Ghost 11",
    18: "Friend Ghost 12",
    19: "Friend Ghost 13",
    20: "Friend Ghost 14",
    21: "Friend Ghost 15",
    22: "Friend Ghost 16",
    23: "Friend Ghost 17",
    24: "Friend Ghost 18",
    25: "Friend Ghost 19",
    26: "Friend Ghost 20",
    27: "Friend Ghost 21",
    28: "Friend Ghost 22",
    29: "Friend Ghost 23",
    30: "Friend Ghost 24",
    31: "Friend Ghost 25",
    32: "Friend Ghost 26",
    33: "Friend Ghost 27",
    34: "Friend Ghost 28",
    35: "Friend Ghost 29",
    36: "Friend Ghost 30",
    37: "Normal Staff Ghost",
    38: "Expert Staff Ghost",
}

country = {
    1: "Japan",
    8: "Anguilla",
    9: "Antigua and Barbuda",
    10: "Argentina",
    11: "Aruba",
    12: "Bahamas",
    13: "Barbados",
    14: "Belize",
    15: "Bolivia",
    16: "Brazil",
    17: "British Virgin Islands",
    18: "Canada",
    19: "Cayman Islands",
    20: "Chile",
    21: "Colombia",
    22: "Costa Rica",
    23: "Dominica",
    24: "Dominican Republic",
    25: "Ecuador",
    26: "El Salvador",
    27: "French Guiana",
    28: "Grenada",
    29: "Guadeloupe",
    30: "Guatemala",
    31: "Guyana",
    32: "Haiti",
    33: "Honduras",
    34: "Jamaica",
    35: "Martinique",
    36: "Mexico",
    37: "Montserrat",
    38: "Netherlands Antilles",
    39: "Nicaragua",
    40: "Panama",
    41: "Paraguay",
    42: "Peru",
    43: "St. Kitts and Nevis",
    44: "St. Lucia",
    45: "St. Vincent and the Grenadines",
    46: "Suriname",
    47: "Trinidad and Tobago",
    48: "Turks and Caicos Islands",
    49: "United States",
    50: "Uruguay",
    51: "US Virgin Islands",
    52: "Venezuela",
    64: "Albania",
    65: "Australia",
    66: "Austria",
    67: "Belgium",
    68: "Bosnia and Herzegovina",
    69: "Botswana",
    70: "Bulgaria",
    71: "Croatia",
    72: "Cyprus",
    73: "Czech Republic",
    74: "Denmark",
    75: "Estonia",
    76: "Finland",
    77: "France",
    78: "Germany",
    79: "Greece",
    80: "Hungary",
    81: "Iceland",
    82: "Ireland",
    83: "Italy",
    84: "Latvia",
    85: "Lesotho",
    86: "Lichtenstein",
    87: "Lithuania",
    88: "Luxembourg",
    89: "F.Y.R of Macedonia",
    90: "Malta",
    91: "Montenegro",
    92: "Mozambique",
    93: "Namibia",
    94: "Netherlands",
    95: "New Zealand",
    96: "Norway",
    97: "Poland",
    98: "Portugal",
    99: "Romania",
    100: "Russia",
    101: "Serbia",
    102: "Slovakia",
    103: "Slovenia",
    104: "South Africa",
    105: "Spain",
    106: "Swaziland",
    107: "Sweden",
    108: "Switzerland",
    109: "Turkey",
    110: "United Kingdom",
    111: "Zambia",
    112: "Zimbabwe",
    113: "Azerbaijan",
    114: "Mauritania (Islamic Republic of Mauritania)",
    115: "Mali (Republic of Mali)",
    116: "Niger (Republic of Niger)",
    117: "Chad (Republic of Chad)",
    118: "Sudan (Republic of the Sudan)",
    119: "Eritrea (State of Eritrea)",
    120: "Djibouti (Republic of Djibouti)",
    121: "Somalia (Somali Republic)",
    128: "Taiwan",
    136: "South Korea",
    144: "Hong Kong",
    145: "Macao",
    152: "Indonesia",
    153: "Singapore",
    154: "Thailand",
    155: "Philippines",
    156: "Malaysia",
    160: "China",
    168: "U.A.E.",
    169: "India",
    170: "Egypt",
    171: "Oman",
    172: "Qatar",
    173: "Kuwait",
    174: "Saudi Arabia",
    175: "Syria",
    176: "Bahrain",
    177: "Jordan",
}
